### ISSUE TITLE
Feature set

### ISSUE THREAD

**Issue by DaleWebb** [DaleWebb/abot-widget#7]
@egtann, I think this needs a little guidance of the purpose of this and its scope.

**Comment by egtann** [comment]
Definitely. The purpose is to allow Abot to receive and reply to emails, just like it does for SMS.

Email introduces a little extra complexity, though. For instance, we'll have to strip/add greetings and signatures, like the following:

* "Dear Dale:"
* "Hi there"
* Yours truly,\nEvan
* Love,
* Best,
* etc.

Since we want that to function the same way across every driver, it's probably best to build that at the interface level. That way the drivers themselves should only need to handle sending and receiving mail.

**Comment by egtann** [comment]
Sure. The purpose is to enable people to quickly add Abot to their websites, whether that's to ask questions about a product, buy airline tickets, etc.

One thing that would be very nice to add to the current implementation is websocket integration, so Abot can communicate back to the user via the response panel (humans responding "as Abot" on the backend) and scheduled events.

In Abot itself, we'd probably want to use an atomic map. We'd use the user's random session token generated client-side as the key (their FlexID), and we'd save their an open websocket connection as the value. Then we can also store a user's random session token client-side with localStorage, so a user can return to a page and retrieve their data. As long as the websocket is available, the message would be sent to the browser. If not, it would be retrievable later by that user by visiting the page again from the same browser.

**Comment by DaleWebb** [comment]
Okay, great!

I'll add that to the README.

That last section opens up some features required - e.g. websockets, storing sessions.  It would be good to add those as issues, to get a todo list going as a guideline.

**Comment by egtann** [comment]
Definitely! I think the only session we need to keep is for websockets. Do you want to create the Github issue?

**Comment by DaleWebb** [comment]
Yeah, I'll create it.

Feel free to add anything too, I'm clear on the vision but perhaps not exactly how to get there
